/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cy_pdl.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Timeout value in microseconds for the 'PLL Enable' API */
#define PLL_ENABLE_TIMEOUT_US       10000ul

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* Manual PLL configuration settings for 16 MHz PLL output clock */
static const cy_stc_pll_manual_config_t PLL_CONFIG_16MHZ =
{
    .feedbackDiv = 26,
    .referenceDiv = 1,
    .outputDiv = 13,
    .lfMode = false,
    .outputMode = CY_SYSCLK_FLLPLL_OUTPUT_AUTO,
};

/* Manual PLL configuration settings for 32 MHz PLL output clock */
static const cy_stc_pll_manual_config_t PLL_CONFIG_32MHZ =
{
    .feedbackDiv = 28,
    .referenceDiv = 1,
    .outputDiv = 7,
    .lfMode = false,
    .outputMode = CY_SYSCLK_FLLPLL_OUTPUT_AUTO,
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function. It initializes the BSP and the retarget-io library.
 *  Later, it shows a menu and prompts the user to choose a test option.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    /* Variable to store the received character through terminal */
    uint8_t uartReadValue;

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdt_obj);
#endif

    /* Initialize the device and board peripherals */
    if (cybsp_init() != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    if (cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    
    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** External Clock (EXT_CLK) Output Code Example ******************\r\n\r\n");

    printf("Choose the following options to change the external clock frequency:\r\n");
    printf("- Send 0 for 16 MHz\r\n");
    printf("- Send 1 for 32 MHz\r\n\r\n");

    for (;;)
    {
        /* Check if data received on UART */
        if (cyhal_uart_getc(&cy_retarget_io_uart_obj, &uartReadValue, 1) == CY_RSLT_SUCCESS)
        {
            /* Check if 0 entered */
            if (uartReadValue == '0')
            {
                Cy_SysClk_PllDisable(SRSS_PLL_200M_0_PATH_NUM);

                if (Cy_SysClk_PllManualConfigure(SRSS_PLL_200M_0_PATH_NUM, &PLL_CONFIG_16MHZ) != CY_SYSCLK_SUCCESS)
                {
                    printf("Error switching to 16 MHz\r\n");
                    continue;
                }

                Cy_SysClk_PllEnable(SRSS_PLL_200M_0_PATH_NUM, PLL_ENABLE_TIMEOUT_US);
                printf("Switched to 16 MHz\r\n");
            }
            /* Check if 1 entered */
            else if (uartReadValue == '1')
            {
                Cy_SysClk_PllDisable(SRSS_PLL_200M_0_PATH_NUM);

                if (Cy_SysClk_PllManualConfigure(SRSS_PLL_200M_0_PATH_NUM, &PLL_CONFIG_32MHZ) != CY_SYSCLK_SUCCESS)
                {
                    printf("Error switching to 32 MHz\r\n");
                    continue;
                }

                Cy_SysClk_PllEnable(SRSS_PLL_200M_0_PATH_NUM, PLL_ENABLE_TIMEOUT_US);
                printf("Switched to 32 MHz\r\n");
            }
        }
    }
}

/* [] END OF FILE */
